import Head from 'next/head'

import Navigation from "../components/Navigation"
import HeroIntro from "../components/HeroIntro"
import Services from '../components/Services'
import FloatComponents from '../components/FloatComponents'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />
      <HeroIntro />
      <Services/>
 <FloatComponents/>
    </>
  )
}
